enum ActionType {
  GET_STUDENTS_REQUESTED = 'APP/STUDENTS/GET_STUDENTS_REQUESTED',
  GET_STUDENTS_SUCCESS = 'APP/STUDENTS/GET_STUDENTS_SUCCESS',
  GET_STUDENTS_FAILED = 'APP/STUDENTS/GET_STUDENTS_FAILED',
  CLEAR_STUDENTS = 'APP/STUDENTS/CLEAR_STUDENTS',
}

export default ActionType;
